### ISSUE TITLE
HTML isn't escaped?

### ISSUE THREAD

**Issue by dooglus** [osTicket/osTicket-1.7#661]
I pasted a chat log into a ticket's response:

```
09:50:42 (55555) <Otoh> Another way to offer daily specials is ...
```

The "&lt;Otoh&gt;" doesn't show up on the ticket.  I presume it is being interpreted as HTML.

Checking the source of the ticket page, I see:

```
<td colspan=3>09:50:42 (55555)  Another way to offer daily specials is ...
```

ie. the "&lt;Otoh&gt;" has been stripped.  It would be better if &lt; was replaced with &amp;lt; etc.

**Comment by greezybacon** [comment]
@dooglas, was this the latest version from the develop branch, or was it 1.7.0?

**Comment by dooglus** [comment]
It's from the released "osTicket-1.7.0.zip" archive.

**Comment by greezybacon** [comment]
Thanks for reporting the issue. It was fixed in #652 and will be included in v1.7.1 due out in about a week or two (a developer preview should be released Monday or Tuesday). If you're in a pinch, you can upgrade to the tip of the develop branch and the issue should be reaolved

**Comment by dooglus** [comment]
It's not a big problem, and I'll wait for the official release.  Just saw a problem and reported it.

Would you prefer I don't report problems in 1.7.0 since they may have been fixed already?

**Comment by greezybacon** [comment]
Please report problems you find. The issue was only discovered and addressed two weeks ago, although 1.7.0 was released April 2nd! You shouldn't assume that your findings have already been addressed

**Comment by greezybacon** [comment]
@dooglus, have you had a chance to retest after upgrading to 1.7.1.*?

**Comment by dooglus** [comment]
I only just upgraded.  I went straight from 1.7.0 to 1.7.2 (I didn't see a link to 1.7.1 on the downloads page, so am guessing it's OK to skip an upgrade step).

The issue is still happening - the <names> are being stripped, but differently.  I no longer see the "td colspan" markup, and don't see a double space where the names were.  I pasted:

```
15:45:36 (1) <dooglus> big square green buttons
15:46:55 (1167) <mercedes> hey all :)
```

into the ticket, but see the following in 'view source':

```
15:45:36 (1) big square green buttons<br/>
15:46:55 (1167) hey all :)<br/>
```

Note: I created this ticket as a test, using 'new ticket', and pasted different bits of chat log with <angle brackets> into both the 'issue' and 'response' fields.  All <names> were stripped from both fields.

The email I got alerting me to the new ticket showed the angle brackets in the 'issue' text, but not in the 'response' text:

```
Our customer care team has created a ticket, #467952 on your behalf, with the following message.

Here's some chat:

15:45:36 (1) <dooglus> big square green buttons
15:46:55 (1167) <mercedes> hey all :)
15:47:39 (2) <Deb> hey merc, how things?
15:48:14 (1167) <mercedes> good, hows things here?

... and here's some more:

15:50:12 (1470)  Hail all
15:50:18 (198561)  wager volume decreasd a lot?
```
