### ISSUE TITLE
Add jQuery-ui dateFormat update from admin configuration

### ISSUE THREAD

**Issue by clonemeagain** [osTicket/osTicket-1.7#789]
Users are confused when all dates are in 'dd/mm/yy' format, but jQuery-UI uses 'mm/dd/yy'.. 

Can we possibly get jQuery-UI to pull this value from the database? Or .. I dunno, rewrite it should an Admin change the date-format?

File in question: https://github.com/osTicket/osTicket-1.7/blob/842ba97d9d54b9f0a969aa755c05cbb3f61495d5/js/jquery-ui-1.8.18.custom.min.js

Not sure how useful anything other than those two alternates are, there must be a way to provide "both" types and have them rewritten by the admin settings. Its 41.5kb in size, we could simply save that file into the database, when an admin changes the date format (or provide a checkbox to select the format) it overwrites the js file.

I was thinking an addition to class.config.php/updateSystemSettings, where any change to the "dateformat" gets reflected in the ui js file.

Forum Topic explaining how to manually correct with screenshots of issue:
http://www.osticket.com/forums/forum/osticket-1-7-latest-release/general-discussions-ab/73957-date-format-due-date

**Comment by greezybacon** [comment]
Thanks for raising this issue. I think it is now fixed in the develop branch and released in 1.7.3

**Comment by greezybacon** [comment]
Can you confirm that this works well in 1.7.3?

**Comment by clonemeagain** [comment]
I added those commits to my 1.7.2.. because I'm not quite ready to rebase again.. and it works. Selecting the date with the DatePicker (even though it displays incorrectly after being selected, will allow you to save it).
I thought it was still broken, because it would display the date as: 

```
15/11/13 H:i
```

after selecting.. (yes, that exact string).

However on Save, it converts it into a pan-global format.. clever!

So yes, it works.

**Comment by greezybacon** [comment]
Interesting. You have `H:i` (_time format_) in your system date format?!

**Comment by clonemeagain** [comment]
Hmm, it would seem so. The ticket thread uses that to display the "time" we received the ticket, staff want that information. Never thought about it being for "date" rather than "time".

Hmm, simple enough, I just changed the formatter used in tickets.inc.php:

``` php
//Format::db_date($row['created']); 
Format::db_datetime($row['created']); 
```

Perfec. ;-)
